/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package rhcad.vgplay.core;

public class vgplayJNI {
  public final static native void delete_Ints(long jarg1);
  public final static native long new_Ints__SWIG_0(int jarg1);
  public final static native long new_Ints__SWIG_1();
  public final static native void Ints_setSize(long jarg1, Ints jarg1_, int jarg2);
  public final static native long new_Ints__SWIG_2(int jarg1, int jarg2);
  public final static native long new_Ints__SWIG_3(int jarg1, int jarg2, int jarg3, int jarg4);
  public final static native int Ints_count(long jarg1, Ints jarg1_);
  public final static native int Ints_get(long jarg1, Ints jarg1_, int jarg2);
  public final static native void Ints_set__SWIG_0(long jarg1, Ints jarg1_, int jarg2, int jarg3);
  public final static native void Ints_set__SWIG_1(long jarg1, Ints jarg1_, int jarg2, int jarg3, int jarg4);
  public final static native int GiCorePlay_DOC_CHANGED_get();
  public final static native int GiCorePlay_SHAPE_APPEND_get();
  public final static native int GiCorePlay_DYN_CHANGED_get();
  public final static native long new_GiCorePlay(int jarg1);
  public final static native void delete_GiCorePlay(long jarg1);
  public final static native int GiCorePlay_getVersion();
  public final static native int GiCorePlay_loadFirstFrame__SWIG_0(long jarg1, GiCorePlay jarg1_);
  public final static native int GiCorePlay_loadFirstFrame__SWIG_1(long jarg1, GiCorePlay jarg1_, String jarg2);
  public final static native int GiCorePlay_loadNextFrame__SWIG_0(long jarg1, GiCorePlay jarg1_, int jarg2);
  public final static native int GiCorePlay_loadPrevFrame(long jarg1, GiCorePlay jarg1_, int jarg2, int jarg3);
  public final static native void GiCorePlay_applyFrame__SWIG_0(long jarg1, GiCorePlay jarg1_, int jarg2);
  public final static native void GiCorePlay_applyFrame__SWIG_1(int jarg1, int jarg2, int jarg3);
  public final static native boolean GiCorePlay_loadFrameIndex(String jarg1, long jarg2, Ints jarg2_);
  public final static native int GiCorePlay_loadNextFrame__SWIG_1(long jarg1, GiCorePlay jarg1_, long jarg2, Ints jarg2_, int jarg3);
  public final static native int GiCorePlay_skipExpireFrame(long jarg1, GiCorePlay jarg1_, long jarg2, Ints jarg2_, int jarg3, int jarg4);
  public final static native boolean GiCorePlay_frameNeedWait(long jarg1, GiCorePlay jarg1_, int jarg2);
}
